import { Box, Film, Gamepad2, Glasses, MonitorSmartphone, Palette } from "lucide-react";
import { categories as Categories } from "@/app/kategori/types/categories";

export const categories: Categories[] = [
  {
    title: "Game Development",
    slug: "game-development",
    description: "Ciptakan dunia imersif dengan mekanik permainan yang seru menggunakan Unity & Unreal.",
    icon: Gamepad2,
    stats: { works: 42, mentors: 4 },
    theme: "purple",
    bgGradient: "from-purple-500/10 to-purple-500/5",
    iconColor: "text-purple-600",
    iconBg: "bg-purple-100",
  },
  {
    title: "UI/UX Design",
    slug: "ui-ux-design",
    description: "Rancang antarmuka intuitif dan pengalaman pengguna yang memikat untuk web & mobile.",
    icon: MonitorSmartphone,
    stats: { works: 35, mentors: 3 },
    theme: "pink",
    bgGradient: "from-pink-500/10 to-pink-500/5",
    iconColor: "text-pink-600",
    iconBg: "bg-pink-100",
  },
  {
    title: "AR / VR",
    slug: "ar-vr",
    description: "Eksplorasi batas realitas dengan teknologi Augmented dan Virtual Reality masa depan.",
    icon: Glasses,
    stats: { works: 18, mentors: 2 },
    theme: "sky",
    bgGradient: "from-sky-500/10 to-sky-500/5",
    iconColor: "text-sky-600",
    iconBg: "bg-sky-100",
  },
  {
    title: "3D Art & Modelling",
    slug: "3d-art",
    description: "Visualisasikan objek dan karakter tiga dimensi yang detail dan realistis.",
    icon: Box,
    stats: { works: 28, mentors: 3 },
    theme: "orange",
    bgGradient: "from-orange-500/10 to-orange-500/5",
    iconColor: "text-orange-600",
    iconBg: "bg-orange-100",
  },
  {
    title: "2D Art & Illustration",
    slug: "2d-art",
    description: "Ekspresikan kreativitas melalui ilustrasi digital, konsep art, dan desain karakter 2D.",
    icon: Palette,
    stats: { works: 50, mentors: 2 },
    theme: "green",
    bgGradient: "from-green-500/10 to-green-500/5",
    iconColor: "text-green-600",
    iconBg: "bg-green-100",
  },
  {
    title: "Multimedia Interaktif",
    slug: "multimedia",
    description: "Gabungkan audio, visual, dan interaksi menjadi karya digital yang komprehensif.",
    icon: Film,
    stats: { works: 60, mentors: 5 },
    theme: "red",
    bgGradient: "from-red-500/10 to-red-500/5",
    iconColor: "text-red-600",
    iconBg: "bg-red-100",
  },
];